### ISSUE TITLE
XHR requests from `https://admin.hub.nuxt.com/embed/database` are being blocked by Safari cross request policies

### ISSUE THREAD

**Issue by brendonmatos** [nuxt-hub/core#34]
## Safari

Visual Error: 
<img width="727" alt="image" src="https://github.com/nuxt-hub/core/assets/11252654/ac6e33d1-00e4-45d6-9b7b-1480b0620732">

Text error:
```
[Error] Not allowed to request resource
[Error] Fetch API cannot load http://localhost:3000/api/_hub/database/query due to access control checks.
```

Nuxt DevTools errors:
<img width="1393" alt="image" src="https://github.com/nuxt-hub/core/assets/11252654/d5eff937-e73f-4431-bdbd-14dacdf7d946">

## Chrome

<img width="1171" alt="image" src="https://github.com/nuxt-hub/core/assets/11252654/2cbf403b-5b93-427a-8515-25fdd263f6d3">

**Comment by pi0** [comment]
(as a related comment, i would suggest that hub modules register a `proxy` route rule to avoid possible cors issues like this)

**Comment by Atinux** [comment]
This is only in development, https://admin.hub.nuxt.com/embed/database is calling https://localhost:3000 without any auth calls.

**Comment by pi0** [comment]
Oh i see then perhaps proxy localhost/_hub to admin.nuxt.com? :) 

Pretty sure we can fix cors issue just mentioning proxy idea as i believe would probably help to resolve this situations..

**Comment by Atinux** [comment]
@brendonmatos the issue seems to be from Safari blocking https://admin.hub.nuxt.com/embed/database to call an insecure URL (http://localhost:3000).

You have two choices:
- Use another browser (Google Chrome)
- Run your development server with `npx nuxt dev --https`

@pi0 proxy is not the solution here as the Nuxt devtools embeds `https://admin.nuxt.com/embed/db?url={local_nuxt_url}`, CORS works well except for Safari when hitting a non-secure endpoint.

**Comment by miguelrk** [comment]
Hey, sorry for commenting on a closed issue. Is it possible to connect to the NuxtHub remote/production instance via its URL `https://admin.nuxt.com/embed/db?url={production_nuxt_url}` and/or its preview instnace? If so, what would be this URL? I'm looking to expose the Drizzle Studio within a Nuxt app via an iframe for admins.
